// <auto-generated />
namespace LeaveRequest.ASP.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addingModelUpdt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingModelUpdt));
        
        string IMigrationMetadata.Id
        {
            get { return "201811251114219_addingModelUpdt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
